spring:
  datasource:
    url: jdbc:mysql://localhost:3306/palettering?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        type: trace
